common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('account-settings/', views.account_settings, name='account_settings'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from pybo.views import base_views

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views, profile_views

app_name = 'pybo'

urlpatterns = [
    #profile_view.py
    path('profile/question/<str:username>/', profile_views.profile_question, name='profile_question'),
    path('profile/answer/<str:username>/', profile_views.profile_answer, name='profile_answer'),
    path('profile/comment/<str:username>/', profile_views.profile_comment, name='profile_comment'),
    path('profile/introduction/<str:username>/', profile_views.profile_introduction, name='profile_introduction'),

    # base_views.py
    path('', base_views.index, name='index'),
    path('category/<int:category_id>/', base_views.index, name='index_with_category'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from pybo.models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['introduction']


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")

common/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from .forms import UserForm
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from pybo.models import Profile
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from .forms import ProfileForm
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView

def password_reset(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            form.save(
                request=request,
                email_template_name='common/password_reset_email.html',
                subject_template_name='common/password_reset_subject.txt',
            )
            return redirect('common:login')
    else:
        form = PasswordResetForm()

    context = {
        'form': form
    }
    return render(request, 'common/password_reset.html', context)


@login_required
def account_settings(request):
    profile, _ = Profile.objects.get_or_create(author=request.user)

    if request.method == 'POST':
        if 'password_submit' in request.POST:
            password_form = PasswordChangeForm(request.user, request.POST)
            if password_form.is_valid():
                password_form.save()
                update_session_auth_hash(request, password_form.user)
                messages.success(request, '비밀번호가 성공적으로 업데이트되었습니다.')
                return redirect('common:account_settings')
        elif 'profile_submit' in request.POST:
            profile_form = ProfileForm(request.POST, instance=profile)
            if profile_form.is_valid():
                profile_form.save()
                messages.success(request, '자기소개가 성공적으로 업데이트되었습니다.')
                return redirect('common:account_settings')
    else:
        password_form = PasswordChangeForm(request.user)
        profile_form = ProfileForm(instance=profile)

    return render(request, 'common/account_settings.html', {'password_form': password_form, 'profile_form': profile_form})


def logout_view(request):
    logout(request)
    return redirect('index')


def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


# User 모델 인스턴스가 저장된 후에 실행될 함수
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(author=instance)

# User 모델 인스턴스가 저장될 때마다 실행될 함수
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

templates/common/account_settings.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3 d-flex">
    <div class="col-10 flex-grow-1">
        <h2>계정설정</h2>
        <ul class="border-bottom"></ul>
        <h5>비밀번호 변경</h5>
        <form action="{% url 'common:account_settings' %}" method="post">
            {% csrf_token %}
            {{ password_form.as_p }}
            <button type="submit" name="password_submit" class="btn btn-primary">비밀번호 수정</button>
        </form>
        <ul class="border-bottom"></ul>
        <h5>자기소개 수정</h5>
        <form action="{% url 'common:account_settings' %}" method="post">
            {% csrf_token %}
            {{ profile_form.as_p }}
            <button type="submit" name="profile_submit" class="btn btn-primary">자기소개 수정</button>
        </form>
    </div>
</div>
{% endblock %}

templates/common/login.html
{% extends "base.html" %}
{% block content %}
{% load socialaccount %}

<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>

</div>
<div class="col-md-6">
        <a role="button" class="btn btn-primary"
           href="{% provider_login_url 'kakao' %}">
            <i class="fas fa-comment">카카오로 로그인</i>
        </a>
    </div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}